# Generated by Django 4.2.7 on 2023-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akanapp', '0002_akanapp_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('akan_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='akanapp',
        ),
    ]
